Update README and setup script

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,52 +1,48 @@
-#!/usr/bin/env sh
+#!/usr/bin/env ruby
+require 'fileutils'
 
-# Set up Rails app. Run this script immediately after cloning the codebase.
+# path to your application root.
+APP_ROOT = File.expand_path('..', __dir__)
 
-# Set up Ruby dependencies via Bundler
-bundle --version &> /dev/null || gem install bundler --no-document
-bundle install
+def system!(*args)
+  system(*args) || abort("\n== Command #{args} failed ==")
+end
 
-failed=false
+FileUtils.chdir APP_ROOT do
+  # This script is a way to setup or update your development environment automatically.
+  # This script is idempotent, so that you can run it at anytime and get an expectable outcome.
+  # Add necessary setup steps to this file.
 
-# Setup application.yml
-echo "\nChecking for config/application.yml"
-tput setaf 2
-if [ -f config/application.yml ]; then
-  echo "application.yml exists, no changes made"
-else
-  echo "Copying over application.yml.sample into application.yml"
-  cp config/application.yml.sample config/application.yml
-fi
-tput sgr0
+  puts '== Installing dependencies =='
+  system! 'gem install bundler --conservative'
+  system('bundle check') || system!('bundle install')
 
-# Setup database
-echo "\nSetting up database"
-if ! [ -f config/database.yml ]; then
-  failed=true
-  tput setaf 1
-  echo "config/database.yml doesn't exist!"
-  echo "Copying over database.yml.sample into database.yml"
-  cp config/database.yml.sample config/database.yml
-  echo "Change your username/password in config/database.yml"
-  tput sgr0
-else
-  tput setaf 2
-  echo "Running rake db:setup"
-  tput sgr0
-  rake db:setup
-  tput setaf 2
-  echo "Database set up!"
-  tput sgr0
-fi
+  # Install JavaScript dependencies
+  # system('bin/yarn')
 
-if $failed; then
-  tput setaf 1
-  echo "\nA command failed! Make the changes suggested and run this script again."
-  tput sgr0
-else
-  tput setaf 2
-  echo "\nDone! Make sure to have guard running :)"
-  echo "Sam recommends installing the LiveReload chrome extension to make developing"
-  echo "awesome (it only works when guard is running)."
-  tput sgr0
-fi
+  puts "\n== Copying sample files =="
+  unless File.exist?('config/database.yml')
+    FileUtils.cp 'config/database.yml.sample', 'config/database.yml'
+  end
+  unless File.exists?('config/application.yml')
+    FileUtils.cp 'config/application.yml.sample', 'config/application.yml'
+  end
+
+  # TODO: HACK AROUND ENSURE TASK
+  puts "\n== Workaround for ensure_semester_and_settings_present =="
+  FileUtils.mv 'config/initializers/ensure_semester_and_settings_present.rb', 'config'
+  # system! 'mv config/initializers/ensure_semester_and_settings_present.rb config'
+
+  puts "\n== Preparing database =="
+  system! 'bin/rails db:setup'
+
+  # TODO: HACK AROUND ENSURE TASK
+  puts "\n== Rollback workaround for ensure_semester_and_settings_present =="
+  FileUtils.mv 'config/ensure_semester_and_settings_present.rb', 'config/initializers'
+
+  puts "\n== Removing old logs and tempfiles =="
+  system! 'bin/rails log:clear tmp:clear'
+
+  puts "\n== Restarting application server =="
+  system! 'bin/rails restart'
+end
